[package]
name = "img2dataset-rs"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
log = "0.4.21"
anyhow = "1.0.82"
ctrlc = "3.4.4"
glob = "0.3.1"
bytes = "1.4.0"
image = "0.24.6"
async-stream = "0.3.5"
csv-async = { version = "1.2", features = ["tokio"] }
futures = "0.3"
opendal = "0.40.0"
reqwest = { version = "0.11.18", features = ["stream", "json"] }
serde = { version = "1.0.164", features = ["derive"] }
tar = "0.4.38"
tokio = { version = "1.28.2", features = ["full"] }
tokio-util = { version = "0.7", features = ["compat"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
rayon = "1.10.0"
serde_json = "1.0.140"

[dependencies.arrow]
version = "55.2.0"

[dependencies.parquet]
version = "55.2.0"
features = ["arrow", "async"]
